[package]
name = "rust_tokenizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_tokenizer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.26.0"
indexmap = "2.7.0"
